spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/utility}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgresql}
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update