spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jwtsample
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgresql}
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000 # 1h